### ISSUE TITLE
注册

### ISSUE THREAD

**Issue by ningsy1017** [skyunBoss/fsxy#2]
app 和admin 公用的一个注册接口？写入到fs_member的数据要同步一份到fs_admin么注册时

**Comment by skyunBoss** [comment]
fs_member 是 app端的用户表
fs_admin 是 后台管理的用户表
不相关的哦

**Comment by skyunBoss** [comment]
fs_member 是 app端的用户表
fs_admin 是 后台管理的用户表
不相关的哦
